import { writeFileSync } from 'fs'

const AREA_X = 6016
const AREA_Y = 3384

const generate = (count: number): string => {
  const out: string[] = []
  for (let i = 0; i < count; i++) {
    const x = Math.floor(Math.random() * AREA_X)
    const y = Math.floor(Math.random() * AREA_Y)
    out.push(`${x}px ${y}px #FFF`)
  }
  return out.join(', ')
}

const shadowsSmall = generate(1000)
const shadowsMedium = generate(400)
const shadowsBig = generate(200)

const content = `// AUTO-GENERATED by scripts/gen-stars.ts — do not edit by hand.
// Regenerate with: bun run scripts/gen-stars.ts
export const shadowsSmall = ${JSON.stringify(shadowsSmall)}
export const shadowsMedium = ${JSON.stringify(shadowsMedium)}
export const shadowsBig = ${JSON.stringify(shadowsBig)}
`

writeFileSync('src/styles/starsData.generated.ts', content)
console.log('Wrote src/styles/starsData.generated.ts')
